;;;;;;;;;; General ;;;;;;;;;;

[Custom Resolution]
; Forces a custom resolution when using the "AUTO" resolution setting in-game.
; You can leave these at 0 if you want your desktop resolution used instead.
Enabled = true
Width = 1280
Height = 960

;;;;;;;;;; Ultrawide/Narrower ;;;;;;;;;;

[Fix Aspect Ratio]
; Fixes aspect ratio and culling issues.
Enabled = true

[Fix FOV]
; Fixes cropped FOV at <16:9.
Enabled = true

[Fix HUD]
; Scales HUD to 16:9.
Enabled = true